export const CORE='http://payroll.pmealab.com/';
export const FRONT_URL='/';
export const BASE_URL='http://payroll.pmealab.com/public/';
export const API_URL=BASE_URL+'api/v1/';
export const EMPLOYEE_PROFILE_IMG=CORE+'uploads/photo/'
export const LOGIN_URL='auth/login';
export const REGISTER_URL='auth/register';
export const FORGOT_PASSWORD='auth/forgot/password';
export const RESET_PASSWORD='auth/reset/password';
export const ADMIN_LOGIN='admin/login';
export const ADMIN_DASHBOARD='admin/dashboard';
export const EMPLOYEE_LOGIN='employee/login';
export const EMPLOYEE_PRESENTY='employee/inout';
export const EMPLOYEE_DASHBOARD='employee/dashboard?emp_id=';
export const EMPLOYEE_APPOINTMENT_LETTER='employee/appointment-letter?emp_id=';
export const EMPLOYEE_ATTENDANCE='employee/attendance?emp_id=';
export const EMPLOYEE_TIMESHEET='employee/timesheet?emp_id=';
export const EMPLOYEE_LEAVE_LIST='employee/leave?emp_id=';
export const EMPLOYEE_LEAVE_ADD='employee/leave/docreate';
export const EMPLOYEE_PAYROLL_LIST='employee/payroll?emp_id=';
export const ADMIN_PAYROLL_LIST='admin/payroll/list';
export const ADMIN_PAYROLL_CHNAGE_STATUS='admin/payroll/status/change';
export const ADMIN_SALARY_CALCULATOR='admin/payroll/calculator/';
export const ADMIN_PAYROLL_EDIT_REQUEST='admin/payroll/request/edit/';
export const ADMIN_PAYROLL_ADD='admin/payroll/create';
export const ADMIN_PAYROLL_UPDATE='admin/payroll/update';
export const ADMIN_PAYROLL_REQUEST_DELETE='admin/payroll/delete/';
export const ADMIN_PAYROLL_REQUEST_SEARCH='admin/payroll/search?';
export const EMPLOYEE_PAYROLL_COLLECTION_LIST='admin/payroll/export';
export const ADMIN_PAYROLL_STMT_SEARCH='admin/payroll/stmt/search?';
export const EMPLOYEE_PAYROLL_SALARYSLIP='employee/payroll/salaryslip';
export const EMPLOYEE_PAYROLL_ADD='employee/payroll/add';
export const EMPLOYEE_PAYROLL_DELETE='employee/payroll/delete/';
export const EMPLOYEE_PAYROLL_SEARCH='employee/payroll/search';
export const EMPLOYEE_PROFILE='employee/profile?emp_id=';
export const EMPLOYEE_PROFILE_UPDATE='employee/profileupd?emp_id=';
export const ADMIN_PROFILE_UPDATE='admin/employee/profileupd';
export const EMPLOYEE_PROFILE_PERSONAL_UPDATE='employee/personal/profileupd';
export const EMPLOYEE_EXSPENSES='employee/exspenses?emp_id=';
export const EMPLOYEE_EXSPENSE_UPDATE='employee/exspense/update';
export const EMPLOYEE_EXSPENSE_EDIT='employee/exspense/edit/';
export const EMPLOYEE_EXSPENSE_CREATE='employee/exspense';
export const EMPLOYEE_EXSPENSE_DELETE='employee/exspense/delete/';
export const EMPLOYEE_EXSPENSE_SEARCH='employee/exspense/search';
export const EMPLOYEE_SLARY_EXPORT='employee/payroll/export';
// export const EMPLOYEE_LOAD_PAYSLIP='employee/payroll/payslip';
export const EMPLOYEE_LOAD_PAYSLIP='admin/payroll/payslip/';
export const ADMIN_ALL_EMPLOYEE='admin/emp';
export const ADMIN_EMP_DELETE='admin/emp/delete/';
export const ADMIN_ALL_EMPLOYEE_SEARCH='admin/emp/search?';
export const ADMIN_SINGLE_EMPLOYEE='admin/emp/single/';
export const ADMIN_CREATE_EMPLOYEE='admin/emp/docreate';
export const ADMIN_UPDATE_EMPLOYEE='admin/emp/update';
export const ADMIN_CHANGE_EMP_STATUS='admin/emp/status';
export const ADMIN_EXSPENSES='admin/exspenses';
export const ADMIN_EXSPENSE_UPDATE='admin/exspense/update';
export const ADMIN_EXSPENSE_EDIT='admin/exspense/edit/';
export const ADMIN_EXSPENSE_CREATE='admin/exspense';
export const ADMIN_EXSPENSE_DELETE='admin/exspense/delete/';
export const ADMIN_EXSPENSE_SEARCH='admin/exspense/search';
export const ADMIN_EXSPENSE_STATUS_CHANGE='admin/exspense/change/status';
export const ADMIN_HOLIDAY_LIST='admin/holiday/list';
export const ADMIN_HOLIDAY_ADD='admin/holiday/create';
export const ADMIN_HOLIDAY_UPDATE='admin/holiday/update';
export const ADMIN_HOLIDAY_DELETE='admin/holiday/delete/';
export const ADMIN_HOLIDAY_EDIT='admin/holiday/edit/';
export const ADMIN_EVENT_LIST='admin/event/list';
export const ADMIN_EVENT_ADD='admin/event/create';
export const ADMIN_EVENT_UPDATE='admin/event/update';
export const ADMIN_EVENT_DELETE='admin/event/delete/';
export const ADMIN_EVENT_EDIT='admin/event/edit/';
export const ADMIN_PERMISSIONS='admin/permissions';
export const ADMIN_PERMISSION_EDIT='admin/permission/edit/';
export const ADMIN_PERMISSION_UPDATE='admin/permission/update';
export const ADMIN_CLIENTS='admin/clients';
export const ADMIN_CLIENT_CREATE='admin/client';
export const ADMIN_CLIENT_EDIT='admin/client/edit/';
export const ADMIN_CLIENT_UPDATE='admin/client/update';
export const ADMIN_CLIENT_DELETE='admin/client/delete/';
export const ADMIN_CLIENT_SEARCH='admin/client/search/';
export const ADMIN_ALLOWANCES='admin/allowances';
export const ADMIN_ALLOWANCE_LIST='admin/allowance/list/';
export const EMPLOYEE_ALLOWANCES='employee/allowances?emp_id=';
export const EMPLOYEE_ALLOWANCE_LIST='employee/allowance/list/';
export const ADMIN_ALLOWANCE_CREATE='admin/allowance';
export const EMPLOYEE_ALLOWANCE_CREATE='employee/allowance';
export const ADMIN_ALLOWANCE_EDIT='admin/allowance/edit/';
export const ADMIN_ALLOWANCE_UPDATE='admin/allowance/update';
export const ADMIN_ALLOWANCE_DELETE='admin/allowance/delete/';
export const ADMIN_ALLOWANCE_SEARCH='admin/allowance/search';
export const ADMIN_ALLOWANCE_LIST_SEARCH='admin/allowance/list/search';
export const EMPLOYEE_ALLOWANCE_SEARCH='employee/allowance/search';
export const ADMIN_ALLOWANCE_STATUS_CHANGE='admin/allowance/change/status';
export const ADMIN_ALLOWANCES_SINGLE='admin/allowances/single?emp_id=';
export const ADMIN_ALLOWANCE_SEARCH_SINGLE='admin/allowance/search/single';
export const ADMIN_LIST_LEAVE='admin/leave';
export const ADMIN_SEARCH_LEAVE='admin/leave/search';
export const EMPLOYEE_SEARCH_LEAVE='employee/leave/search';
export const ADMIN_REPORT_LEAVE='admin/leave/reportprocess';
export const ADMIN_ADD_LEAVE='admin/leave/docreate';
export const ADMIN_EDIT_LEAVE='admin/leave/edit/';
export const ADMIN_DELETE_LEAVE='admin/leave/delete/';
export const ADMIN_UPDATE_LEAVE='admin/leave/update';
export const ADMIN_TIMESHEET_REPORT='admin/timesheet/reportprocess';
export const ADMIN_TIMESHEET_LIST='admin/timesheet';
export const ADMIN_TIMESHEET_SEARCH='admin/timesheet/search?emp_id=';
export const ADMIN_TIMESHEET_CREAT='admin/timesheet/docreate';
export const ADMIN_TIMESHEET_UPDATE='admin/timesheet/update';
export const ADMIN_TIMESHEET_EDIT='admin/timesheet/edit/';
export const ADMIN_TIMESHEET_DELETE='admin/timesheet/delete/';
export const ADMIN_GUEST_ATTENDANCE='admin/attendance/guests';
export const ADMIN_SEARCH_ATTENDANCE='admin/guest/search?query=';
export const ADMIN_ADD_ATTENDANCE='admin/attendance/guest/docreate';
export const ADMIN_EDIT_ATTENDANCE='admin/attendance/guest/edit/';
export const ADMIN_UPDATE_ATTENDANCE='admin/attendance/guest/update';
export const ADMIN_DELETE_ATTENDANCE='admin/attendance/delete/';
export const ADMIN_ATTENDANCE='admin/attendance';
export const ADMIN_ATTENDANCE_SEARCH='admin/attendance/search?query=';
export const ADMIN_ATTENDANCE_CREATE='admin/attendance/docreate';
export const ADMIN_ATTENDANCE_EDIT='admin/attendance/edit/';
export const ADMIN_ATTENDANCE_UPDATE='admin/attendance/update';
export const ADMIN_ATTENDANCE_DELETE='admin/attendance/delete/';
export const ADMIN_ATTENDANCE_REPORT='admin/attendance/reportprocess';
export const ADMIN_ATTENDANCE_DATEVIEW='admin/attendance/calendar-view';
export const ADMIN_COMPANY_DEPT='admin/company/dept';
export const ADMIN_COMPANY_DEPT_DELETE='admin/company/dept/delete/';
export const ADMIN_COMPANY_DEPT_EDIT='admin/company/dept/edit/';
export const ADMIN_COMPANY_DEPT_UPDATE='admin/dept/update';
export const ADMIN_ADD_COMPANY_DEPT='admin/dept/docreate';
export const ADMIN_COMPANY_DESIGN='admin/company/posting';
export const ADMIN_COMPANY_DESIGN_EDIT='admin/company/posting/edit/';
export const ADMIN_COMPANY_DESIGN_DELETE='admin/company/posting/delete/';
export const ADMIN_COMPANY_DESIGN_UPDATE='admin/posting/update';
export const ADMIN_COMPANY_POSTING_CREATE='admin/posting/docreate';
export const ADMIN_ADD_PAYROLL='admin/payroll';
export const ADMIN_REPORT_PAYROLL='admin/payroll/generate';
export const ADMIN_PAYROLL_CREATE='admin/payroll/savedata';
export const ADMIN_PAYROLL_STATEMENT_VIEW='admin/payroll/statement-view';
export const ADMIN_PAYROLL_STATEMENT='admin/payroll/statements';
export const ADMIN_STATEMENT_FILTER='admin/payroll/statements/filter';
export const ADMIN_STATEMENT_SEARCH='admin/payroll/statements/search';
export const SETTINGS='admin/settings';
export const SETTING_UPDATE='admin/setting/update';
export const USER_PROFILE_TAX_UPDATE='admin/user/profile/update';
export const USER_PROFILE_BANK_UPDATE='admin/user/profile/bank/update'
export const ADD_APPONTMENT='admin/emp/docreate';
export const FRONTEND_URL= FRONT_URL;
export const EMPLOYEE_LOGIN_URL=FRONTEND_URL+'employee/login';
export const ADMIN_LOGIN_URL=FRONTEND_URL+'admin/login';
export const EMPLOYEE_FORGOT_PWD='employee/forgot/password';
export const EMPLOYEE_RESET_PWD='employee/reset/password';
export const EMPLOYEE_VALIDATE_PWD_LINK='employee/reset/email/';

// payroll
export const ADMIN_PAYROLL_LISTS='admin/list/payroll';
export const ADMIN_PAYROLL_LIST_SINGLE='admin/list/payroll/single';
export const ADMIN_EMP_PAYROLL_EDIT='admin/list/payroll/edit/';
export const ADMIN_EMP_PAYROLL_UPDATE='admin/list/payroll/update';
export const ADMIN_EMP_PAYSLIP_GENERATE='admin/list/payslip/generate';
export const ADMIN_PAYROLL_LIST_SEARCH='admin/list/payroll/search/';
export const ADMIN_PAYSLIPS_SEARCH='admin/list/payslip/search/';
export const ADMIN_PAYSLIPS_SINGLE_SEARCH='admin/list/payslip/single/search/';
export const ADMIN_PAYSLIPS_BULK_GENERATE='admin/list/payslip/bulk/generate/';
export const ADMIN_EMP_PLASLIP_EDIT='admin/list/payslip/edit/';
export const ADMIN_EMP_PAYSLIP_UPDATE='admin/list/payslip/update';
export const ADMIN_EMP_PAYSLIP_DELETE='admin/list/payslip/delete/';
export const ADMIN_PAYSLIP_PAID='admin/list/payslip/paid/';
export const ADMIN_PAYSLIP_CHANGE_STATUS='admin/list/payslip/change/status'

// employee playslip
export const EMPLOYEE_PAYSLIPS_LOAD='employee/list/payslip/';
export const PAYROLL_GET_EMPLOYEE='admin/list/payroll/emp/';
export const ADMIN_ADD_EMP_PAYROLL='admin/list/payroll/add';

// Al & ded Table
export const ADMIN_LOAD_PAYROLL_SETTING = 'admin/payroll/settings';
export const ADMIN_EDIT_ALLOWANCE_SETTING = 'admin/payroll/setting/allowance/edit/';
export const ADMIN_EDIT_DEDUCT_SETTING = 'admin/payroll/setting/deduct/edit/';
export const ADMIN_DELETE_ALLOWANCE_SETTING = 'admin/payroll/setting/allowance/delete/';
export const ADMIN_DELETE_DEDUCT_SETTING = 'admin/payroll/setting/deduct/delete/';
export const ADMIN_ADD_PAYROLL_ALLOWANCE_SETTING = 'admin/payroll/setting/allowance/create';
export const ADMIN_ADD_PAYROLL_DEDUCT_SETTING = 'admin/payroll/setting/deduct/create';
export const ADMIN_UPDATE_PAYROLL_ALLOWANCE = 'admin/payroll/setting/allowance/update';
export const ADMIN_UPDATE_PAYROLL_DEDUCT = 'admin/payroll/setting/deduct/update';

export const ADMIN_LOAD_PROJECTS = 'admin/projects';
export const ADMIN_PROJECT_EDIT = 'admin/project/edit/';
export const ADMIN_PROJECT_ADD = 'admin/project/docreate';
export const ADMIN_PROJECT_UPDATE = 'admin/project/update';
export const ADMIN_PROJECT_DELETE = 'admin/project/delete/';
export const ADMIN_PROJECT_STATUS_CHANGE = 'admin/project/status/change';
